services:
  chat:
    image: thunfischchat:latest
    build: .
    container_name: "chat"
    restart: "unless-stopped"
    environment:
      PORT: 3000
    ports:
      - "3000:3000/tcp"
    tty: true
    stdin_open: true